# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 07:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_imio_ts1_datasources', '0003_auto_20170323_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imiots1datasources',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
